name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: extractions/setup-just@v2

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: just build

      - name: Lint
        run: just lint

      - name: Test
        run: just test
